In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
A=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [3]:
print(a.shape)
print(a)
print(a.T)

(6,)
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [4]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
A.shape

(2, 6)

In [6]:
np.dot(a,b) #produit scalaire entre a et b

217

In [7]:
a@b

217

In [8]:
np.dot(A,a)#a considéré en colonne M(2,6)xM(6,1)=>M(2,1)

array([ 91, 217])

In [9]:
A @ a

array([ 91, 217])

In [10]:
np.dot(a,A.T)#a considéré en ligne M(1,6)xM(6,2)=>M(1,2)

array([ 91, 217])

In [11]:
a @ A.T

array([ 91, 217])